version: 2
updates:
  - package-ecosystem: gradle
    directory: /
    schedule:
      interval: weekly
      day: thursday
    target-branch: '1.0.x'
    ignore:
      - dependency-name: '*'
        update-types:
          - version-update:semver-major
          - version-update:semver-minor
    open-pull-requests-limit: 10
    labels:
      - 'type: dependency-upgrade'
    groups:
      development-dependencies:
        update-types:
          - patch
        patterns:
          - com.gradle.enterprise
          - com.github.spotbugs
          - io.spring.*
          - org.ajoberstar.grgit

  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
      day: friday
    target-branch: '1.0.x'
    labels:
      - 'type: task'
    groups:
      development-dependencies:
        patterns:
          - '*'
