version: 2
registries:
  spring-milestones:
    type: maven-repository
    url: https://repo.spring.io/milestone

updates:

  - package-ecosystem: gradle
    target-branch: main
    directory: /
    schedule:
      interval: "daily"
      # 9am UTC-5
      time: "14:00"
    ignore:
      - dependency-name: org.junit:junit-bom
        update-types:
          - version-update:semver-major
      - dependency-name: org.mockito:mockito-bom
        update-types:
          - version-update:semver-major
      - dependency-name: '*'
        update-types:
          - version-update:semver-major
          - version-update:semver-minor
    labels:
      - 'type: dependency-upgrade'
    registries:
      - spring-milestones
    groups:
      development-dependencies:
        update-types:
          - patch
        patterns:
          - com.gradle.enterprise
          - com.github.spotbugs
          - io.spring.*
          - org.ajoberstar.grgit

  - package-ecosystem: gradle
    target-branch: 1.2.x
    directory: /
    schedule:
      interval: "daily"
      # 10am UTC-5
      time: "15:00"
    ignore:
      - dependency-name: org.junit:junit-bom
        update-types:
          - version-update:semver-major
      - dependency-name: org.mockito:mockito-bom
        update-types:
          - version-update:semver-major
      - dependency-name: '*'
        update-types:
          - version-update:semver-major
          - version-update:semver-minor
    labels:
      - 'type: dependency-upgrade'
    registries:
      - spring-milestones
    groups:
      development-dependencies:
        update-types:
          - patch
        patterns:
          - com.gradle.enterprise
          - com.github.spotbugs
          - io.spring.*
          - org.ajoberstar.grgit

  - package-ecosystem: github-actions
    target-branch: main
    directory: /
    schedule:
      interval: "weekly"
      day: "saturday"
    labels:
      - 'type: task'
    groups:
      development-dependencies:
        patterns:
          - '*'

  - package-ecosystem: github-actions
    target-branch: 1.2.x
    directory: /
    schedule:
      interval: "weekly"
      day: "saturday"
    labels:
      - 'type: task'
    groups:
      development-dependencies:
        patterns:
          - '*'
